### ISSUE TITLE
Box64 breaks GDB break on address

### ISSUE THREAD

**Issue by mogery** [ptitSeb/box64#134]
When I set a break to, for example `0x7ffff5c3eda0`, and the program executes on that address, GDB can't stop execution. Instead, box64 prints `<PID>|Warning, ignoring unsupported Int 3 call @0x7ffff5c3eda1`.

I'm running `gdb /path/to/box64 /path/to/target`. Is this not the intended way to debug?

**Comment by ptitSeb** [comment]
Debugging apps is tricky. I usualy use a trace enable build, and 1st create a dump of the code (using `BOX64_TRACE=0-1 BOX64_TRACE_FILE=dump.txt BOX64_DYNAREC_DUMP=2 /path/to/target`), Then I use arm debugger to get more insight of the crash / watever going on, or I use `BOX64_JITGDB=1 /path/to/target` to have gdb launched at first crash (because the Dynarec use SEGFAULT as internal macanism, it's tedious to debug a program on dynarec). Once on the crash, you can have a look around and see whant's wrong. Also, I use `FindDynablockFromNativeAddress(...)` function to get the Dynablock from the crash address and check if it's from Dynarec'd code, and also `getX64Address(...)` to get the actual x86 IP address (so I can check on the Dump what block is running). Check `src/libtools/signal.c`, in `my_box64signalhandler(...)` how to use all those functions. I call the function directly from gdb to get precise informations...

**Comment by mogery** [comment]
Cool, thanks! That works great when debugging a crash, but sadly, I'm trying to gain insight on things being slow, not things crashing. I guess I'll have to use a different approach.

**Comment by ptitSeb** [comment]
I use `sudo perf top` on a separate terminal / ssh. I think the slowiness at load is symbol resolution with version tracking. Not sure why as I haven't investigate much, but last time I checked it was around this things

**Comment by ptitSeb** [comment]
> > Regular "Int 3" are for now ignored, but could be redirected to a SIGTRAP (look at line 242 of `src/emu/x64int3.c`)
> 
> I did take out the `0 &&` blocking the `if` there, but unfortunately GDB still wouldn't pick up on the breakpoint.

Yeah, the SIGTRAP is probably not what gdb is expecting here (just an actual "int3", so a `__builtin_trap()` maybe or something like that)

**Comment by mogery** [comment]
> Yeah, the SIGTRAP is probably not what gdb is expecting here (just an actual "int3", so a `__builtin_trap()` maybe or something like that)

Alright, I'll poke at it sometime.

**Comment by rajdakin** [comment]
Is this fixed now?

**Comment by LukeShortCloud** [comment]
There are hints in the read me file now on how to deal with this.

https://github.com/ptitSeb/box64?tab=readme-ov-file#usage

Closing as resolved.
