### ISSUE TITLE
Buffer overflow in RunF0

### ISSUE THREAD

**Issue by Gumix** [ptitSeb/box64#140]
Array index 1 is past the end of the array (which contains 1 element):

https://github.com/ptitSeb/box64/blob/36bfcd21d4ff11db13ba8487d7d1f8323cee7610/src/emu/x64run0f.c#L1226

**Comment by rajdakin** [comment]
Closing this, since this is a hypothetical breakage ("a compiler *may break* this code" because this is UB, which means all compilers which are widely used, ie GCC and Clang, do the only logical thing and *don't* break this code), combined with no solution provided on how to fix this (a `reg64_t` should really be 64 bits long, so replacing the `1` with a `2` in the definition would really not be ideal). Also, this code is present in the interpreter, which is almost never used.

Note that the code is still used today: https://github.com/ptitSeb/box64/blob/42ce1a3b61c291f08968eaa2ae35d90761ada4cc/src/emu/x64run0f.c#L1715

If you have a good solution (which doesn't involve changing the size of the `reg64_t` or duplicating the `GetEd` code, both of which are bad solutions), please reopen this issue. Until then, this is marked as "won't fix".
