### ISSUE TITLE
Required file not found in the Beyond All Reason appimage on M1

### ISSUE THREAD

**Issue by m1m1k4tz** [ptitSeb/box64#1411]
When using the fedora package box64-asahi it gives me `Error loading needed lib libgcc_s.so.1` and when compiling the latest version it says `/tmp/.mount_BeyondjBuxXM/AppRun: line 43: /tmp/.mount_BeyondjBuxXM/beyond-all-reason: cannot execute: required file not found`

**Comment by ptitSeb** [comment]
This lib `libgcc_s.so.1` should be installed with box64 if you built from sources. Are you using latest box64 (becasue I fixed some issue on non-4K pagesize lately), and do build from source or use some package?

**Comment by m1m1k4tz** [comment]
The libgcc error only comes up with the box64-asahi package on fedora when I compile and install it myself it doesn’t get that far and gives me the /tmp/ error

**Comment by ptitSeb** [comment]
c++ library are not wrapped and need to be emulated. That's why there are installed (libgcc_s.so.1 and libstdc++.so.6, among a few other), when installing box64 from sources.

I suppose the box64 package doesn't install them, as it's not a proper way to install x86_64 library using package.
You'll need to either installs those libs by hand, or using multi-arch and install libstdc++.so.6 from x86_64 architecture (no idea how to do that on fedora)

**Comment by ptitSeb** [comment]
When you build from source, don't forget to restart binfmt service after the make install, or x86_64 program will not be redirected utomaticaly to box64 (and you'll get error like the /tmp/ one)

**Comment by m1m1k4tz** [comment]
Okay thanks that fixed it but there’s a new error now so I’ll open a new issue
