### ISSUE TITLE
Is there any web browser can be used ?

### ISSUE THREAD

**Issue by minhaozh** [ptitSeb/box64#181]
I wanna try to use a web browser on ras-pi4b ,by box64,but I've try many like midori,tor and firefox,
none of them succeed...
I would like to ask, has anyone successfully used a certain browser? If so, please let me know.. Any browser will do.

**Comment by calvinweb** [comment]
emmmm why no use native arm64 browser?

**Comment by rajdakin** [comment]
Brower-based programs (which include electron) are very unstable on box64 and are unlikely to run. However, as mentioned by lin-calvin, you can simply use a native browser (I know chromium and firefox both have native ARM versions that you can download on Raspberry PI).
Closing for now as stale since you have not answered for ~2.5 years.
