### ISSUE TITLE
Raspberry PI 5 Box64 

### ISSUE THREAD

**Issue by bargmy** [ptitSeb/box64#1825]
i have Raspberry PI OS **Lite** x64 and im using xfce.
the box64 for rpi5 doesnt exist on the page of pre-built deb files.
so if anyone have the proper tutorial of how to install it please tell me :)

**Comment by jon-freed** [comment]
Try this:

1. Go to the repository's home page (https://github.com/ptitSeb/box64)
2. Click on the link for "Compilation instructions can be found here" (https://github.com/ptitSeb/box64/blob/main/docs/COMPILE.md)
3. If you don't want to do the full compile/make and you trust somebody else to do that for you, then scroll down to the section "Pre-build Packages" (https://github.com/ptitSeb/box64/blob/main/docs/COMPILE.md#pre-build-packages)
4. Copy the commands there into a .sh file then execute it.
5. Reboot
6. Start your x86 64 program.  The box64 will intercept the program's execution and do its magic.

**Comment by FoxbitDreamtail** [comment]
Another option if you're up for is just installing the Pi Apps application, finding Box64, and then installing it there. Alternatively, since you're probably going to try using Steam anyway, if you installed Steam, it would install Box 64 and Box 86 for you, so that you can run 32 and 64-bit Linux programs in conjunction with being able to run Steam and its games. Proton does work with steam, but I heavily recommend that you try using native first before relying on any sort of proton build due to there being some serious issues with both unity and unreal, unless it's native.

**Comment by LukeShortCloud** [comment]
@bargmy If you need any more help building and/or installing Box64, please let us know! Closing as complete for now as the suggestions above should help.
