### ISSUE TITLE
Can you support armhf (ARM32) ?

### ISSUE THREAD

**Issue by iHad168** [ptitSeb/box64#1891]
Can you support armhf (ARM32) ?
I found that more and more ARM hardware CPUs can only run 64-bit apps.
Box86 is cannot run on which 64-bit CPU.

**Comment by rajdakin** [comment]
Your question isn't clear. Are you asking whether it is possible to use box64 on ARM32 machines, or to use box86 on ARM64?

`box86` is a software to run 32bits x86 software on 32bits hardware. `box64` is the same for 64bits x86_64 software on 64bits hardware. Recently, an early version of `box32` is being developed, which allows 32bits x86 software to run on 64bits hardware (ie, most modern ARM CPUs), though it is still off by default since it's too unstable.
As a side note: `box32` is *not* a standalone binary, but part of `box64`. To have `box32` available, you need to add it to the configuration step of box64 (`cmake -DBOX32=1`). `box64` will then be able to run both x86 and x86_64 software (though with quite a few issues currently, a lot of work still needs to be done).

The other way around, using `box86` to run 64bits software on 32bits hardware, is not being considered currently.

**Comment by iHad168** [comment]
Thank you for your detailed reply.
I asked Box32 (that is, running the ARM 32-BIT program on the ARM64 device).
Because I found that my Android device can only run 64-BIT programs.
Box86 requires my device to run the ARM32 instruction set.
I will try `cmake -DBOX32=1`

**Comment by LukeShortCloud** [comment]
If you have any specific issues with Box32, please feel free to open a separate GitHub Issue. Closing as complete.
