### ISSUE TITLE
Hmm help optimize this game?

### ISSUE THREAD

**Issue by gurachan** [ptitSeb/box64#2058]
![Screenshot_2024-11-23-19-46-56-601_com frost benchmark](https://github.com/user-attachments/assets/f7c18be6-9f97-414a-8e4f-a4f6de8d9942)

Do you have idea why this game struggling to run? 

Its a simple unity 2d game :'( im using proot frost winlator with latest box64. Other info is already at the overlay. 

![Screenshot_2024-11-23-19-56-36-473_com frost benchmark-edit](https://github.com/user-attachments/assets/659b07a7-b80e-41dc-b43a-9429b24b9a66)

The fps drop after u on the field like on screenshot

**Comment by ptitSeb** [comment]
NOTE: I removed the link.

Did you try Perfomance settings instead of Compatible?
Also, it's not a "simple" 2D game. It's a 3D game, using a complex 3D Engine (Unity). But the GPU seems idle so, it's not a GPU bottleneck anyway, so you should try performance, or performance + strongmem=1 because it's unity and strongmem is usualy needed.

**Comment by gurachan** [comment]
> NOTE: I removed the link.
> 
> Did you try Perfomance settings instead of Compatible? Also, it's not a "simple" 2D game. It's a 3D game, using a complex 3D Engine (Unity). But the GPU seems idle so, it's not a GPU bottleneck anyway, so you should try performance, or performance + strongmem=1 because it's unity and strongmem is usualy needed.

Hmm tried it now . still low fps 13-16 fps :'( is it cpu bottleneck? Sad.. aight feel free to close this xD maybe one day it run smooth.

**Comment by ptitSeb** [comment]
English only please.

**Comment by King6696** [comment]
This is a Snapdragon 8s gen 3 problem. Fps is low and GPU is loaded at 10-15%
