### ISSUE TITLE
Crash in .NET application on Wine

### ISSUE THREAD

**Issue by jg00dman** [ptitSeb/box64#227]
This is probably pushing the boundaries a bit but I tried running Logos Bible Software 9 which is a .Net 4.8 app on my raspberry pi. I copied a working install from my x64 intel desktop. All config was the same as the working on. I got wine running to winecfg. The app launched and showed the startup splash screen and then crashed showing the attached terminal output.

The process was terminalted due to an internal error in the .NET Runtime at IP 0000000001345591 with exit code 80131506.
There is some little bit about the exit code here: https://docs.microsoft.com/en-us/answers/questions/323834/executionengineexception-and-exit-code-80131506.html

I'm sorry I don't understand it though. I assume this is a bug in box64 because the program runs to a winehq silver standard on my desktop with kubuntu.

Alternatively could it be to do with dependencies etc? 

Any help much appreciated!

![photo_2022-02-06_13-12-49](https://user-images.githubusercontent.com/13243799/152682575-d1a0f185-3a11-4009-b53c-eebdc224bd4b.jpg)

**Comment by rajdakin** [comment]
Is this fixed now?
Also, please copy and paste the logs instead of providing a screenshot. To format it properly, surround the logs with triple backquotes in empty lines like so:
\`\`\`
\<the logs here>
\`\`\`
This yields:
```
<the logs here>
```
The logs you have provided above are insufficient to trace back the source of the issue. Also, if you still have an issue,  here is this program you are running available? Is it free?

**Comment by LukeShortCloud** [comment]
The latest versions of Box64 works great with a lot of Unity and other .NET applications/games. If you continue to run into issues with Logos Bible Software 9, feel free to re-open this GitHub Issue. Closing as resolved.
