### ISSUE TITLE
ST0.d!=0.0   can we judge double value != 0.0 through this?

### ISSUE THREAD

**Issue by ifquant** [ptitSeb/box64#228]
hi, thanks for your great work. just some question.
void arm_fscale(x64emu_t* emu)
{
    if(ST0.d!=0.0)  //  can we judge double value != 0.0 through this?
        ST0.d *= exp2(trunc(ST1.d));
}

**Comment by ptitSeb** [comment]
That should be correct yes, why, you have some issue with this?

**Comment by ifquant** [comment]
thanks for reply.  not still have issue with this, just learned fron classs ,say that ‘if( abs(f) <= 1e-15 )，then f=0’’,i will test it later..
i got there because i am going through all the helper function, and check is there more Optimization could be done.

**Comment by rajdakin** [comment]
Closing as the "issue" was solved.
(Also, what you learned in class is correct in the context of nearly every use of `double` since floating-point numbers have rounding issues, which means that you almost certainly need to check for near-zero instead of exactly-zero. Here however, I suspect that the opcode(s) using this function require the value of `ST0` to be not-exactly-positive-zero, not just far-from-zero, which is also a relative statement that needs to be studied case by case. Comparisons between FP numbers are nearly always tricky, but here due to the nature of box64 we can simplify things.)
