### ISSUE TITLE
run spec 2006 CFP , resut diff with program run on x64

### ISSUE THREAD

**Issue by ifquant** [ptitSeb/box64#356]
dear ptitSeb  :
i run many spec 2006 x64 program on arm plat.(PHYTIUM), for example:  416.gamess, 434.zeusmp,  437.leslie3d and so on, 
the output result very different with run on x64. almost float value always output 0.000000.

i want to fix this problem,  can you give some advice about this? :)

**Comment by ptitSeb** [comment]
well, first, try to run without dynarec (using `BOX64_DYNAREC=0` env. var) to see if you get correct result there.
If you have the correct result, that means there is an issue specificaly in the Dynarec.
If it's not the correct result, than the bug is elsewere (maybe in the interpretor, in a core functionnaly, or in a wrapped function).

Also, make sure you use latest box64 version, I fix bugs often.

**Comment by ifquant** [comment]
may be myStackAlign did not process all format  properly ? like "%+-#.*e" this format ? i will try to do some test.

**Comment by ptitSeb** [comment]
yes, that could be the case indeed.

**Comment by LukeShortCloud** [comment]
Support for this has been improved. Closing as resolved.
