### ISSUE TITLE
[RV64] Problematic handling of overflow flag with ORI instruction

### ISSUE THREAD

**Issue by xctan** [ptitSeb/box64#568]
Upon reviewing my code of `emit_sar32c()`, I found that flags are forgotten to be shifted, and then discovered the fact that setting OF with ORI instruction is causing headache.

RISC-V spec says that:

> ANDI, ORI, XORI are logical operations that perform bitwise AND, OR, and XOR on register rs1 and the sign-extended 12-bit immediate and place the result in rd.

Unfortunately, the overflow flag of x86 FLAGS register is located at the 12th least significant bit. If we try to do ORI with 0x0800, the immediate operand is actually 0xFFFFFFFFFFFFF800 (sign extend 0x0800 to 64 bits), thus destroying flags in higher bits.

I've discussed some ideas with @ksco:

1. `CLEAR_FLAGS` still works, and all flags are cleared.
2. 3 reserved flags exists in lower flag bits, so we may hack one of these.
3. flags higher than OF are not so useful, is there any chance that we can safely ignore them?

**Comment by ptitSeb** [comment]
Ah yeah, I wanted to check because I remember some flags are "high".

F_OF will not be set often, because, as you said, it's not used a lot. But the computation should be here and should be exact. 
So F_OF maybe should be removed from the CLEAR_FLAGS, because we don't want to clear bits 32:13 of xFlags

Don't worry about generated code: there is a lot of optimisation to avoid to compute flags if possible: so the code to copute F_OF (of F_PF in fact), will be rarelly used.

**Comment by ptitSeb** [comment]
about the flags conversion.... I'll think about it, not sure yet...

**Comment by ksco** [comment]
We may need to make it correct first, and then we can think about how to optimize it later (or never..).

**Comment by ptitSeb** [comment]
I pushed something.

I initialy wanted to just handle `F_OF` as-is... but it feeled cumbersome... So I implemented the "substitue" scenario, using `F_res3`
Seems fine for now. Use `F_OF2` internaly, and use `ADJUST_FROM11` or `ADJUST_TO11` when loading/storing to the actual `eflags` of the `emu` structure.
